# Use postgres/example user/password credentials

version: '3.1'
services:
  db:
    image: postgres
    container_name: inventory_db
    restart: always
    volumes:
      - ./docker-data/db-data:/var/lib/postgresql/data
      - /home/petebdeblois/repos/SQL_inventory_backend/sources:/home/admin/sources
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: 'GMT-5'
      PGTZ: 'GMT-5'
    ports:
      - 5432:5432
  adminer:
    container_name: adminer
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8090:8080
